DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS word;

CREATE TABLE player (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  active INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE game (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ended TIMESTAMP
);

CREATE TABLE word (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id INTEGER NOT NULL,
  word TEXT NOT NULL,
  FOREIGN KEY (game_id) REFERENCES game (id)
);
